### ISSUE TITLE
Shooting Full-Auto when plugging in Battery

### ISSUE THREAD

**Issue by Bischi1997** [t238/Digital_Trigger_Unit#14]
I am creating this issue, because I was told so by the aliexpress seller.

So I installed the Mosfet T238 v1.7 optical for v2 Gearboxes in my gun. It worked for about 4 shots, then it switched to fullauto.
I had to unplug the device from the battery. Now as soon as I connect the battery it starts to shoot in full auto.
The device was installed as provided on the website (https://t238.net/tutorial).

Any help on this or is my suspicion correct, that the mosfet is fried?

Here's also a video: [Video of plugging in a Battery](https://imgur.com/G1tHwOm)

**Comment by joao-wivo** [comment]
I had the exact same problem on the Bluetooth version!

Video:
https://www.youtube.com/watch?v=NayC5RcX3nY

**Comment by Bischi1997** [comment]
FYI, the unit is defective and I did a dispute on aliexpress.
